import { Product, Category } from "@shared/schema";

export const mockCategories: Category[] = [
  { id: 1, name: "Athletic Shoes", icon: "fas fa-running", isHot: false },
  { id: 2, name: "Leather Shoes", icon: "fas fa-shoe-prints", isHot: false },
  { id: 3, name: "Boots", icon: "fas fa-hiking", isHot: false },
  { id: 4, name: "Loafers", icon: "fas fa-user-tie", isHot: false },
  { id: 5, name: "High Heels", icon: "fas fa-female", isHot: false },
  { id: 6, name: "Sneakers", icon: "fas fa-fire", isHot: true },
  { id: 7, name: "Sandals", icon: "fas fa-school", isHot: false },
  { id: 8, name: "Backpacks", icon: "fas fa-briefcase", isHot: false },
  { id: 9, name: "Belts", icon: "fas fa-hat-cowboy", isHot: false },
  { id: 10, name: "Handbags", icon: "fas fa-shopping-bag", isHot: false },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Gaming Headset Pro RGB",
    description: "High-end gaming headset with RGB lighting and premium sound quality",
    price: "149.99",
    originalPrice: "199.99",
    category: "Electronics",
    brand: "ProGamer",
    imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "5.0",
    reviewCount: 45,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 25,
  },
  {
    id: 2,
    name: 'MacBook Pro 14" M3 Chip',
    description: "Latest MacBook Pro with M3 chip for professional use",
    price: "1999.99",
    originalPrice: null,
    category: "Computers",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "4.8",
    reviewCount: 89,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 3,
    name: "iPhone 15 Pro Max 256GB",
    description: "Latest iPhone with titanium design and advanced camera system",
    price: "1199.99",
    originalPrice: null,
    category: "Smartphones",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "5.0",
    reviewCount: 156,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 4,
    name: "Apple Watch Series 9 GPS",
    description: "Advanced fitness tracking and health monitoring smartwatch",
    price: "399.99",
    originalPrice: null,
    category: "Wearables",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "5.0",
    reviewCount: 203,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 5,
    name: "AirPods Pro 2nd Gen",
    description: "Premium wireless earbuds with active noise cancellation",
    price: "249.99",
    originalPrice: null,
    category: "Audio",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "5.0",
    reviewCount: 78,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 6,
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with tactile switches",
    price: "129.99",
    originalPrice: null,
    category: "Accessories",
    brand: "Corsair",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "4.3",
    reviewCount: 34,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 7,
    name: "External Hard Drive 2TB",
    description: "Portable external storage for all your files and backups",
    price: "89.99",
    originalPrice: null,
    category: "Storage",
    brand: "Western Digital",
    imageUrl: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "5.0",
    reviewCount: 67,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 8,
    name: "4K HD Webcam with Mic",
    description: "Professional webcam for streaming and video conferencing",
    price: "79.99",
    originalPrice: null,
    category: "Cameras",
    brand: "Logitech",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=400&h=300",
    rating: "4.2",
    reviewCount: 23,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
];

export const featuredProducts: Product[] = [
  {
    id: 20,
    name: "Smart Watch Series 9",
    description: "Advanced fitness tracking and health monitoring",
    price: "429.00",
    originalPrice: null,
    category: "Wearables",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.8",
    reviewCount: 156,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 21,
    name: "Gaming Laptop Pro",
    description: "High-performance laptop for gaming and creative work",
    price: "1599.00",
    originalPrice: null,
    category: "Laptops",
    brand: "ASUS",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.7",
    reviewCount: 89,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 22,
    name: "4K Webcam HD",
    description: "Professional quality webcam for streaming and video calls",
    price: "149.00",
    originalPrice: null,
    category: "Cameras",
    brand: "Logitech",
    imageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.6",
    reviewCount: 74,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 23,
    name: "Wireless Charger Stand",
    description: "Fast wireless charging stand for smartphones",
    price: "59.99",
    originalPrice: null,
    category: "Accessories",
    brand: "Belkin",
    imageUrl: "https://images.unsplash.com/photo-1609592842693-8ad5c7d6b02c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.5",
    reviewCount: 92,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 24,
    name: "Bluetooth Speaker",
    description: "Portable wireless speaker with premium sound quality",
    price: "89.99",
    originalPrice: null,
    category: "Audio",
    brand: "JBL",
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.4",
    reviewCount: 68,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
];

export const hotProducts: Product[] = [
  {
    id: 25,
    name: "PlayStation 5",
    description: "Next-generation gaming console with ultra-high speed SSD",
    price: "499.99",
    originalPrice: null,
    category: "Gaming",
    brand: "Sony",
    imageUrl: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "5.0",
    reviewCount: 245,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 26,
    name: "RTX 4090 Graphics Card",
    description: "Ultimate gaming graphics card for 4K performance",
    price: "1599.00",
    originalPrice: null,
    category: "Graphics Cards",
    brand: "NVIDIA",
    imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.9",
    reviewCount: 167,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 27,
    name: "Gaming Chair Pro",
    description: "Ergonomic gaming chair with RGB lighting and premium comfort",
    price: "299.99",
    originalPrice: null,
    category: "Furniture",
    brand: "SecretLab",
    imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.8",
    reviewCount: 134,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 28,
    name: "MacBook Pro M3",
    description: "Professional laptop with M3 chip for ultimate performance",
    price: "1999.00",
    originalPrice: null,
    category: "Laptops",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "5.0",
    reviewCount: 198,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 29,
    name: "Smart Home Hub",
    description: "Central hub for all your smart home devices and automation",
    price: "119.99",
    originalPrice: null,
    category: "Smart Home",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.7",
    reviewCount: 89,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
];

export const flashSaleProducts: Product[] = [
  {
    id: 30,
    name: "iPhone 14 Pro",
    description: "Latest iPhone with Pro camera system and A16 Bionic chip",
    price: "999.00",
    originalPrice: "1099.00",
    category: "Smartphones",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.9",
    reviewCount: 324,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 9,
  },
  {
    id: 31,
    name: "Gaming Headset",
    description: "Professional gaming headset with 7.1 surround sound",
    price: "89.99",
    originalPrice: "129.99",
    category: "Audio",
    brand: "HyperX",
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.7",
    reviewCount: 156,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 31,
  },
  {
    id: 32,
    name: "Tablet 10-inch",
    description: "High-resolution tablet perfect for work and entertainment",
    price: "249.00",
    originalPrice: "329.00",
    category: "Tablets",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.6",
    reviewCount: 98,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 24,
  },
  {
    id: 33,
    name: "Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with tactile switches",
    price: "79.99",
    originalPrice: "119.99",
    category: "Accessories",
    brand: "Corsair",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.8",
    reviewCount: 234,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 33,
  },
  {
    id: 34,
    name: "Wireless Mouse Pro",
    description: "Precision wireless mouse with long battery life",
    price: "39.99",
    originalPrice: "59.99",
    category: "Accessories",
    brand: "Logitech",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.5",
    reviewCount: 167,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 33,
  },
];

export const recentlyViewedProducts: Product[] = [
  {
    id: 25,
    name: "Gaming Headset Pro",
    description: "Professional gaming headset with RGB lighting",
    price: "89.99",
    originalPrice: "129.99",
    category: "Audio",
    brand: "HyperX",
    imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=300&h=300&fit=crop&crop=center",
    rating: "4.6",
    reviewCount: 143,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 31,
  },
  {
    id: 26,
    name: "Ultrabook Laptop 13\"",
    description: "Lightweight laptop for productivity and travel",
    price: "899.99",
    originalPrice: null,
    category: "Computers",
    brand: "Dell",
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300&h=300&fit=crop&crop=center",
    rating: "4.5",
    reviewCount: 87,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 27,
    name: "Wireless Mouse Pro",
    description: "Ergonomic wireless mouse for professional use",
    price: "49.99",
    originalPrice: "69.99",
    category: "Accessories",
    brand: "Logitech",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&h=300&fit=crop&crop=center",
    rating: "4.7",
    reviewCount: 203,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 29,
  },
  {
    id: 28,
    name: "4K Webcam HD",
    description: "Professional webcam for streaming and video calls",
    price: "129.99",
    originalPrice: null,
    category: "Cameras",
    brand: "Logitech",
    imageUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=300&h=300&fit=crop&crop=center",
    rating: "4.8",
    reviewCount: 156,
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 29,
    name: "Bluetooth Speaker",
    description: "Portable speaker with premium sound quality",
    price: "79.99",
    originalPrice: "99.99",
    category: "Audio",
    brand: "JBL",
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=300&h=300&fit=crop&crop=center",
    rating: "4.6",
    reviewCount: 124,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 20,
  },
  {
    id: 30,
    name: "Smart Watch Series 8",
    description: "Advanced fitness tracking and health monitoring",
    price: "349.99",
    originalPrice: null,
    category: "Wearables",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=300&h=300&fit=crop&crop=center",
    rating: "4.9",
    reviewCount: 89,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 31,
    name: "Mechanical Keyboard RGB",
    description: "Premium mechanical keyboard with RGB backlighting",
    price: "129.99",
    originalPrice: "179.99",
    category: "Accessories",
    brand: "Corsair",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&h=300&fit=crop&crop=center",
    rating: "4.7",
    reviewCount: 198,
    isNew: false,
    isBestseller: false,
    isOnSale: true,
    discountPercentage: 28,
  },
];

export const recentProducts: Product[] = [
  {
    id: 9,
    name: "iPad Air 256GB",
    description: "Powerful tablet for work and creativity",
    price: "599.99",
    originalPrice: null,
    category: "Tablets",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=300&h=300&fit=crop&crop=center",
    rating: "4.8",
    reviewCount: 45,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 10,
    name: "DSLR Camera Kit",
    description: "Professional photography camera with lens kit",
    price: "1299.99",
    originalPrice: null,
    category: "Cameras",
    brand: "Canon",
    imageUrl: "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=300&h=300&fit=crop&crop=center",
    rating: "4.9",
    reviewCount: 32,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 11,
    name: "PlayStation 5",
    description: "Next-generation gaming console",
    price: "499.99",
    originalPrice: null,
    category: "Gaming",
    brand: "Sony",
    imageUrl: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=300&h=300&fit=crop&crop=center",
    rating: "5.0",
    reviewCount: 234,
    isNew: true,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 12,
    name: '4K Smart TV 55"',
    description: "Ultra HD smart television with streaming capabilities",
    price: "899.99",
    originalPrice: null,
    category: "TVs",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=300&h=300&fit=crop&crop=center",
    rating: "4.6",
    reviewCount: 89,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 13,
    name: 'Gaming Monitor 27"',
    description: "High refresh rate monitor for competitive gaming",
    price: "349.99",
    originalPrice: null,
    category: "Monitors",
    brand: "ASUS",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=300&h=300&fit=crop&crop=center",
    rating: "4.7",
    reviewCount: 67,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 14,
    name: "WiFi 6 Router",
    description: "High-speed wireless router with advanced security",
    price: "199.99",
    originalPrice: null,
    category: "Networking",
    brand: "ASUS",
    imageUrl: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=300&h=300&fit=crop&crop=center",
    rating: "4.4",
    reviewCount: 43,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 15,
    name: "Wireless Earbuds Pro",
    description: "Premium noise-canceling wireless earbuds",
    price: "179.99",
    originalPrice: null,
    category: "Audio",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=300&h=300&fit=crop&crop=center",
    rating: "4.8",
    reviewCount: 156,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 16,
    name: "Mechanical Keyboard RGB",
    description: "Premium mechanical keyboard with RGB backlighting",
    price: "129.99",
    originalPrice: null,
    category: "Accessories",
    brand: "Corsair",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&h=300&fit=crop&crop=center",
    rating: "4.7",
    reviewCount: 89,
    isNew: true,
    isBestseller: false,
    isOnSale: false,
    discountPercentage: 0,
  },
];

export const bestSellerProducts: Product[] = [
  {
    id: 15,
    name: "Gaming Mouse Pro",
    description: "Precision gaming mouse with customizable buttons",
    price: "79.99",
    originalPrice: null,
    category: "Accessories",
    brand: "Razer",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "5.0",
    reviewCount: 50,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 16,
    name: "Mechanical Keyboard",
    description: "Professional mechanical keyboard for gaming and typing",
    price: "129.99",
    originalPrice: null,
    category: "Accessories",
    brand: "Corsair",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.8",
    reviewCount: 32,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 17,
    name: "Smartphone X Pro",
    description: "Latest flagship smartphone with advanced features",
    price: "899.99",
    originalPrice: null,
    category: "Smartphones",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "5.0",
    reviewCount: 120,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 18,
    name: "Wireless Earbuds Pro",
    description: "Premium noise-canceling wireless earbuds",
    price: "159.99",
    originalPrice: null,
    category: "Audio",
    brand: "Sony",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.9",
    reviewCount: 85,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
  {
    id: 19,
    name: "Gaming Headset Elite",
    description: "Professional gaming headset with surround sound",
    price: "199.99",
    originalPrice: null,
    category: "Audio",
    brand: "SteelSeries",
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&h=80",
    rating: "4.7",
    reviewCount: 67,
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    discountPercentage: 0,
  },
];
